export enum BookingStatus {
    PENDING_PAYMENT = "PENDING_PAYMENT",
    CONFIRMED = "CONFIRMED",
    VENDOR_ASSIGNED = "VENDOR_ASSIGNED",
    VENDOR_ENROUTE = "VENDOR_ENROUTE",
    ARRIVED = "ARRIVED",
    IN_PROGRESS = "IN_PROGRESS",
    SERVICE_ENDED = "SERVICE_ENDED",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED"
}

export enum PaymentStatus {
    PENDING = "PENDING",
    PAID = "PAID",
    FAILED = "FAILED",
    REFUNDED = "REFUNDED"
}
